"""Extended rent affordability content per city."""

EXTENDED = {
    ("texas", "austin"): {
        "state_abbr": "TX",
        "default_income": 75000,
        "default_debt": 350,
        "default_family": 1,
        "default_save": 15,
        "median_rent": 1780,
        "rent_studio": 1420,
        "rent_1br": 1750,
        "rent_2br": 2280,
        "col_index": 108,
        "afford_score": 74,
        "utilities": 195,
        "transport": 370,
        "groceries": 400,
        "tax_takehome": 0.78,
        "compare_note": "Dallas",
        "compare_slug": "texas/dallas",
        "col_link": "/living/housing/cost-of-living-by-city/texas/austin",
        "house_link": "/living/housing/how-much-house-can-i-afford/texas/austin",
        "salary_link": "/living/lifestyle/comfortable-salary/texas/austin",
        "moving_link": "/living/housing/moving-cost-calculator/texas/austin",
        "tax_link": "/hourly-to-salary-after-tax/state/texas/",
        "neighborhoods": [
            ("Downtown", 2500, 100000, "Walkable core; premiums for views and new builds."),
            ("South Congress", 2100, 85000, "Trendy corridor; older stock mixed with new."),
            ("North Austin", 1700, 70000, "Tech corridor; good transit options on some corridors."),
            ("Round Rock", 1500, 60000, "Suburb north; longer commute, more space per dollar."),
        ],
        "income_expansions": [
            (75000, 1800, "Can you afford $1,800 rent on $75k in Austin?", "Yes. A $75k salary generally supports rent around $1,800–$1,900 while maintaining room for savings. At 30% of gross, the ceiling is $1,875/month before utilities."),
            (100000, 2200, "Is $2,200 rent affordable on $100k in Austin?", "It can work as a stretch budget if debt is low and you still save 10–15% of take-home. Comfortable rent on $100k is closer to $2,000–$2,300 depending on debt and savings goals."),
            (50000, 1250, "How much rent on $50k in Austin?", "Plan near $1,250/month at the 30% gross rule — often a studio or roommate situation in central zip codes."),
        ],
        "tiers": [
            ("Survival budget", 55000, "Studio or roommate; tight margin for savings."),
            ("Comfortable budget", 75000, "1BR in many neighborhoods with modest savings."),
            ("Very comfortable", 100000, "1BR premium areas or 2BR in suburbs."),
            ("Premium lifestyle", 150000, "Downtown or large 2BR with strong savings rate."),
        ],
        "narrative": [
            "Austin rent cooled slightly after the 2022 peak but still runs above Houston and San Antonio. Tech wages help, yet list prices in popular corridors stay sticky.",
            "No Texas state income tax boosts take-home pay versus coastal metros. Property tax matters more if you buy — renters still face rising insurance pass-throughs in some buildings.",
            "Many newcomers underestimate commute time on I-35 and MoPac. A cheaper suburb can erase savings if you add tolls and gas.",
        ],
        "faqs": [
            ("Is $2,000 rent affordable on a $75k salary in Austin?", "It is at the top of the comfortable band for many renters. Add utilities and parking — if total housing passes 35% of take-home, treat it as stretch rent."),
            ("What salary do I need for a 2-bedroom apartment in Austin?", "Median 2BR near $2,280 implies roughly $91k gross at the 30% rule — more if you want savings room and low debt."),
            ("How much should I spend on rent in Austin?", "Start at 30% of gross for landlord math, then cap at 30% of take-home for your real budget. Use the lower number."),
            ("Is Austin rent higher than Dallas?", "Yes on median 1BR in most years. Dallas offers more suburban stock below $1,600; Austin's tech corridor pulls medians up."),
        ],
        "related": [
            ("Is $75k enough to live in Austin?", "/living/lifestyle/comfortable-salary/texas/austin/is-75k-enough-to-live-in-austin"),
            ("Is $100k enough to live in Austin?", "/living/lifestyle/comfortable-salary/texas/austin/is-100k-enough-to-live-in-austin"),
            ("Comfortable salary in Austin", "/living/lifestyle/comfortable-salary/texas/austin"),
            ("Cost of living in Austin", "/living/housing/cost-of-living-by-city/texas/austin"),
            ("How much house can I afford in Austin?", "/living/housing/how-much-house-can-i-afford/texas/austin"),
            ("Moving cost calculator — Austin", "/living/housing/moving-cost-calculator/texas/austin"),
        ],
    },
    ("texas", "dallas"): {
        "state_abbr": "TX",
        "default_income": 76000,
        "default_debt": 400,
        "default_family": 1,
        "default_save": 15,
        "median_rent": 1550,
        "rent_studio": 1240,
        "rent_1br": 1550,
        "rent_2br": 1980,
        "col_index": 102,
        "afford_score": 75,
        "utilities": 200,
        "transport": 360,
        "groceries": 390,
        "tax_takehome": 0.78,
        "compare_note": "Austin",
        "compare_slug": "texas/austin",
        "col_link": "/living/housing/cost-of-living-by-city/texas/dallas",
        "house_link": "/living/housing/how-much-house-can-i-afford/texas/dallas",
        "salary_link": "/living/lifestyle/comfortable-salary/texas/dallas",
        "moving_link": "/living/housing/moving-cost-calculator/texas/dallas",
        "tax_link": "/hourly-to-salary-after-tax/state/texas/",
        "neighborhoods": [
            ("Uptown", 2200, 90000, "Walkable; young professional crowd; parking fees common."),
            ("Deep Ellum", 1850, 75000, "Arts district; older units; check noise and parking."),
            ("Frisco", 1700, 70000, "Suburb north; family-oriented; toll roads."),
            ("Oak Cliff", 1400, 58000, "More affordable pockets; research block-by-block."),
        ],
        "income_expansions": [
            (76000, 1650, "Can you afford $1,650 rent on $76k in Dallas?", "Yes — that sits near the comfortable band for many DFW renters with moderate debt."),
            (100000, 2100, "Is $2,100 rent affordable on $100k in Dallas?", "Often yes as a stretch in Uptown or Plano. Comfortable target is closer to $2,000–$2,300 gross-rule max."),
            (50000, 1250, "How much rent on $50k in Dallas?", "Near $1,250/month at 30% gross — roommate or outer-ring suburb is common."),
        ],
        "tiers": [
            ("Survival budget", 52000, "Roommate or far suburbs; thin savings."),
            ("Comfortable budget", 76000, "1BR in many DFW neighborhoods."),
            ("Very comfortable", 100000, "Uptown 1BR or suburban 2BR."),
            ("Premium lifestyle", 140000, "Large 2BR in prime zip codes."),
        ],
        "narrative": [
            "Dallas–Fort Worth spreads across many tax districts and commute patterns. Median rent stays below Austin in most surveys.",
            "No state income tax helps take-home pay. Sales tax and toll roads still add to monthly cost.",
            "Job growth pulled some suburbs above the regional median — check Frisco and Plano quotes against your office location.",
        ],
        "faqs": [
            ("Is $1,800 rent affordable on $75k in Dallas?", "Generally yes — near the comfortable ceiling before utilities."),
            ("What salary for a 2-bedroom in Dallas?", "Near $79k gross at 30% rule for a $1,980 median 2BR — higher with savings goals."),
            ("How much should I spend on rent in Dallas?", "Use 30% of take-home after debt and savings — often $1,400–$1,700 on median incomes."),
            ("Is Dallas rent higher than Austin?", "Usually no on median 1BR. Austin runs hotter in urban core listings."),
        ],
        "related": [
            ("Is $75k enough to live in Dallas?", "/living/lifestyle/comfortable-salary/texas/dallas/is-75k-enough-to-live-in-dallas"),
            ("Is $100k enough to live in Dallas?", "/living/lifestyle/comfortable-salary/texas/dallas/is-100k-enough-to-live-in-dallas"),
            ("Comfortable salary in Dallas", "/living/lifestyle/comfortable-salary/texas/dallas"),
            ("Cost of living in Dallas", "/living/housing/cost-of-living-by-city/texas/dallas"),
            ("How much house can I afford in Dallas?", "/living/housing/how-much-house-can-i-afford/texas/dallas"),
            ("Moving cost calculator — Dallas", "/living/housing/moving-cost-calculator/texas/dallas"),
        ],
    },
    ("new-york", "new-york-city"): {
        "state_abbr": "NY",
        "default_income": 95000,
        "default_debt": 500,
        "default_family": 1,
        "default_save": 10,
        "median_rent": 3400,
        "rent_studio": 2900,
        "rent_1br": 3400,
        "rent_2br": 4500,
        "col_index": 158,
        "afford_score": 52,
        "utilities": 230,
        "transport": 280,
        "groceries": 550,
        "tax_takehome": 0.68,
        "compare_note": "Chicago",
        "compare_slug": "illinois/chicago",
        "col_link": "/living/housing/cost-of-living-by-city/new-york/new-york-city",
        "house_link": "/living/housing/how-much-house-can-i-afford/new-york/new-york-city",
        "salary_link": "/living/lifestyle/comfortable-salary/new-york/new-york-city",
        "moving_link": "/living/housing/moving-cost-calculator/new-york/new-york-city",
        "tax_link": "/hourly-to-salary-after-tax/state/new-york/",
        "neighborhoods": [
            ("Manhattan core", 4200, 140000, "Highest rents; broker fees common."),
            ("Brooklyn (Williamsburg)", 3500, 115000, "Popular with creatives; 1BR premiums."),
            ("Queens (Astoria)", 2400, 85000, "More space; solid transit."),
            ("Bronx", 2100, 75000, "Lower median; longer commutes to Midtown."),
        ],
        "income_expansions": [
            (95000, 2400, "Can you afford $2,400 rent on $95k in NYC?", "Possible in outer boroughs as a stretch. Manhattan often needs $120k+ for similar comfort."),
            (120000, 3000, "Is $3,000 rent affordable on $120k?", "Near gross-rule max. State and city tax shrink take-home — budget closer to $2,400–$2,700 comfortable."),
            (75000, 1900, "How much rent on $75k in NYC?", "Near $1,875 gross cap — usually roommates or far outer borough."),
        ],
        "tiers": [
            ("Survival budget", 70000, "Roommates; long commutes."),
            ("Comfortable budget", 95000, "Outer borough 1BR or Manhattan studio."),
            ("Very comfortable", 120000, "Brooklyn 1BR or Queens 2BR."),
            ("Premium lifestyle", 180000, "Manhattan 1BR+ with savings room."),
        ],
        "narrative": [
            "NYC rent is quoted net of broker fees in many listings. Budget one month or more at lease signing.",
            "State and city income tax cut take-home versus Texas or Florida. Use net pay in the calculator, not gross alone.",
            "Transit replaces a car for many households — but MetroCard and rideshare still belong in the monthly plan.",
        ],
        "faqs": [
            ("Is $2,000 rent affordable on $75k in NYC?", "Only with roommates or heavy stretch — total housing often exceeds 40% of take-home."),
            ("What salary for a 2-bedroom in NYC?", "Median 2BR near $4,500 implies $180k gross at 30% — often dual income."),
            ("How much should I spend on rent in NYC?", "Many planners use 30% of take-home; NYC renters often exceed it — know your stretch limit."),
            ("Is NYC rent higher than Chicago?", "Yes — median 1BR is nearly double Chicago in most indexes."),
        ],
        "related": [
            ("Is $100k enough to live in NYC?", "/living/lifestyle/comfortable-salary/new-york/new-york-city/is-100k-enough-to-live-in-new-york-city"),
            ("Comfortable salary in NYC", "/living/lifestyle/comfortable-salary/new-york/new-york-city"),
            ("Cost of living in NYC", "/living/housing/cost-of-living-by-city/new-york/new-york-city"),
            ("How much house can I afford in NYC?", "/living/housing/how-much-house-can-i-afford/new-york/new-york-city"),
            ("Moving cost calculator — NYC", "/living/housing/moving-cost-calculator/new-york/new-york-city"),
        ],
    },
    ("florida", "miami"): {
        "state_abbr": "FL",
        "default_income": 90000,
        "default_debt": 450,
        "default_family": 1,
        "default_save": 12,
        "median_rent": 2300,
        "rent_studio": 1950,
        "rent_1br": 2300,
        "rent_2br": 3100,
        "col_index": 118,
        "afford_score": 61,
        "utilities": 225,
        "transport": 340,
        "groceries": 430,
        "tax_takehome": 0.77,
        "compare_note": "Tampa",
        "compare_slug": "florida/tampa",
        "compare_col_link": "/living/housing/cost-of-living-by-city/florida/tampa",
        "col_link": "/living/housing/cost-of-living-by-city/florida/miami",
        "house_link": "/living/housing/how-much-house-can-i-afford/florida/miami",
        "salary_link": "/living/lifestyle/comfortable-salary/florida/miami",
        "moving_link": "/living/housing/moving-cost-calculator/florida/miami",
        "tax_link": "/hourly-to-salary-after-tax/state/florida/",
        "neighborhoods": [
            ("Brickell", 3200, 110000, "High-rise core; parking often extra."),
            ("Wynwood", 2600, 90000, "Trendy; newer inventory."),
            ("Coral Gables", 2400, 85000, "Leafy; family-friendly."),
            ("Hialeah", 1900, 68000, "More affordable; check commute."),
        ],
        "income_expansions": [
            (90000, 2250, "Can you afford $2,250 rent on $90k in Miami?", "Near comfortable for many renters without heavy debt. Insurance and parking can push total housing higher."),
            (75000, 1900, "Is $1,900 rent affordable on $75k?", "Stretch in central zip codes; workable in Hialeah or with a roommate."),
            (120000, 3000, "How much rent on $120k in Miami?", "Gross cap near $3,000 — Brickell 1BR territory with tight savings if debt is high."),
        ],
        "tiers": [
            ("Survival budget", 60000, "Roommate; far west or north."),
            ("Comfortable budget", 90000, "1BR in many neighborhoods."),
            ("Very comfortable", 120000, "Brickell or 2BR in suburbs."),
            ("Premium lifestyle", 160000, "Waterfront or large 2BR with savings."),
        ],
        "narrative": [
            "Miami rent runs well above Tampa and Orlando. Hurricane insurance and flood zones affect total housing cost even for renters via building fees.",
            "No state income tax helps take-home, but car insurance and parking in Brickell add up fast.",
            "Seasonal rent swings matter — winter quotes can exceed summer listings in some buildings.",
        ],
        "faqs": [
            ("Is $2,500 rent affordable on $90k in Miami?", "Stretch level for many — total housing with utilities may exceed 35% of take-home."),
            ("What salary for a 2-bedroom in Miami?", "Median 2BR near $3,100 implies $124k gross at 30%."),
            ("How much should I spend on rent in Miami?", "Cap take-home at 30% including utilities and renters insurance."),
            ("Is Miami rent higher than Dallas?", "Yes — median 1BR is roughly 40–50% higher."),
        ],
        "related": [
            ("Is $100k enough to live in Miami?", "/living/lifestyle/comfortable-salary/florida/miami/is-100k-enough-to-live-in-miami"),
            ("Comfortable salary in Miami", "/living/lifestyle/comfortable-salary/florida/miami"),
            ("Cost of living in Miami", "/living/housing/cost-of-living-by-city/florida/miami"),
            ("How much house can I afford in Miami?", "/living/housing/how-much-house-can-i-afford/florida/miami"),
            ("Moving cost calculator — Miami", "/living/housing/moving-cost-calculator/florida/miami"),
        ],
    },
    ("illinois", "chicago"): {
        "state_abbr": "IL",
        "default_income": 82000,
        "default_debt": 400,
        "default_family": 1,
        "default_save": 15,
        "median_rent": 1850,
        "rent_studio": 1480,
        "rent_1br": 1850,
        "rent_2br": 2400,
        "col_index": 112,
        "afford_score": 70,
        "utilities": 195,
        "transport": 310,
        "groceries": 420,
        "tax_takehome": 0.74,
        "compare_note": "NYC",
        "compare_slug": "new-york/new-york-city",
        "col_link": "/living/housing/cost-of-living-by-city/chicago",
        "house_link": "/living/housing/how-much-house-can-i-afford",
        "salary_link": "/living/lifestyle/comfortable-salary/illinois/chicago",
        "moving_link": "/living/housing/moving-cost-calculator/chicago",
        "tax_link": "/hourly-to-salary-after-tax/state/illinois/",
        "neighborhoods": [
            ("Loop", 2400, 95000, "Downtown; smaller units; walk to work."),
            ("Lincoln Park", 2200, 88000, "Popular; parks and transit."),
            ("Logan Square", 1900, 76000, "Young professionals; dining scene."),
            ("Hyde Park", 1600, 65000, "Near university; south side anchor."),
        ],
        "income_expansions": [
            (82000, 1850, "Can you afford $1,850 rent on $82k in Chicago?", "Yes — near median and comfortable for many with moderate debt."),
            (100000, 2200, "Is $2,200 rent affordable on $100k?", "Often a stretch in Lincoln Park; comfortable in Logan Square or Hyde Park."),
            (60000, 1500, "How much rent on $60k in Chicago?", "Near $1,500 gross cap — roommate or south/west side common."),
        ],
        "tiers": [
            ("Survival budget", 55000, "Roommate; outer neighborhoods."),
            ("Comfortable budget", 82000, "1BR in many city neighborhoods."),
            ("Very comfortable", 100000, "Lincoln Park 1BR or 2BR in suburbs."),
            ("Premium lifestyle", 140000, "Loop luxury or large 2BR."),
        ],
        "narrative": [
            "Chicago offers big-city amenities below coastal rent. Flat state income tax still reduces take-home versus Texas.",
            "Winter heating can spike utility bills — ask for average monthly utility from the landlord.",
            "Neighborhood safety and commute vary block by block — visit at rush hour before you sign.",
        ],
        "faqs": [
            ("Is $2,000 rent affordable on $75k in Chicago?", "Stretch for many — comfortable closer to $1,650–$1,875 on that income."),
            ("What salary for a 2-bedroom in Chicago?", "Median 2BR near $2,400 implies $96k gross at 30%."),
            ("How much should I spend on rent in Chicago?", "30% of take-home after debt — often $1,500–$1,900 on median salaries."),
            ("Is Chicago rent higher than Dallas?", "Slightly higher on median 1BR; much lower than NYC."),
        ],
        "related": [
            ("Comfortable salary in Chicago", "/living/lifestyle/comfortable-salary/illinois/chicago"),
            ("Cost of living in Chicago", "/living/housing/cost-of-living-by-city/chicago"),
            ("How much house can I afford", "/living/housing/how-much-house-can-i-afford"),
            ("Moving cost calculator — Chicago", "/living/housing/moving-cost-calculator/illinois/chicago"),
        ],
    },
}
